# Generated by Django 4.1.7 on 2023-05-03 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 11, 35, 42, 828554, tzinfo=datetime.timezone.utc)),
        ),
    ]
