# Generated by Django 4.1.7 on 2023-05-06 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0013_pessoa_delete_jogo_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 14, 46, 16, 727061, tzinfo=datetime.timezone.utc)),
        ),
    ]
