# Generated by Django 4.1.7 on 2023-05-06 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0016_alter_noticia_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 15, 15, 12, 93632, tzinfo=datetime.timezone.utc)),
        ),
    ]
