# Generated by Django 4.1.7 on 2023-05-07 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0020_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='clube',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 7, 11, 18, 15, 505294, tzinfo=datetime.timezone.utc)),
        ),
    ]
