# Generated by Django 4.1.7 on 2023-05-10 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0026_alter_jogo_data_alter_jogo_hora_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 13, 19, 19, 198436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2023, 5, 10, 13, 19, 19, 198436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 10, 13, 19, 19, 198436, tzinfo=datetime.timezone.utc)),
        ),
    ]
