# Generated by Django 4.1.7 on 2023-05-12 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0030_alter_jogo_data_alter_jogo_hora_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 38, 39, 989846, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2023, 5, 12, 15, 38, 39, 989863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 15, 38, 39, 989041, tzinfo=datetime.timezone.utc)),
        ),
    ]
